### ISSUE TITLE
suggestion: Inlet naming

### ISSUE THREAD

**Issue by georules** [enjalot/Inlet#16]
It seems to me that Inlet has two meanings with regards to Tributary:
1. Inlet the library that provides some UI elements integrated with codemirror
2. An Inlet on Tributary, which is a hosted site showing some code and a visualization

I think we should consider changing the name of this library to remove this confusion.

**Comment by enjalot** [comment]
With building-blocks this naming issue wont be as prevelant https://github.com/enjalot/building-blocks
I'm going to be deprecating tributary with the release of building-blocks. I think this library can stand on its own now!

**Comment by curran** [comment]
It's great to see fresh activity here, the Inlet library is so cool!
