### ISSUE TITLE
Numbers always changing to a different number onmouseup

### ISSUE THREAD

**Issue by Azeirah** [enjalot/Inlet#18]
When scrubbing a number around, to say, 832, when you then release the mouse button, the value in the editor changes to maybe double that amount.

Fiddling around with the inlet code a bit, I found that commenting out

[slider.addEventListener("mouseup", onSlideMouseUp);](https://github.com/enjalot/Inlet/blob/master/src/inlet.js#L40)

Fixes this for me, I haven't checked it out on other browsers though.

This was on Firefox developer edition 35

**Comment by georules** [comment]
I confirm this behavior in firefox 29 (haven't opened ff in a while haha) and firefox 35.  This seems to be specific to firefox's implementation of "range".  This does not occur in Chrome.  We should decide if onSlideMouseUp is needed for correct function in Chrome.

**Comment by enjalot** [comment]
This seems to be an issue with the interface to the firefox slider, and the way it handles events.

I fixed it temporarily by checking for firefox and not binding to the mouseup event when using firefox. So we can still have the feature in chrome (that when you mouseup it resets the slider so you can keep sliding) and things work decently in FF.
