### ISSUE TITLE
Trouble parsing.. something

### ISSUE THREAD

**Issue by gelicia** [enjalot/Inlet#19]
Sorry for the vague subject, but I'm not sure exactly what it's having trouble with. All I know is clicking inside one of the gradient.append lines causes my CPU to spike, so there's probably an infinite loop in there somewhere.

Full example : http://tributary.io/inlet/6d068bfa2d5e1f5b03c2 

```
 .attr('id', 'master').call(
      function(gradient) {
        gradient.append('svg:stop').attr('offset', '0%').attr('style', 'stop-color:rgb(0,229,91);stop-opacity:1');
        gradient.append('svg:stop').attr('offset', '100%').attr('style', 'stop-color:rgb(0,229,91);stop-opacity:0');
      });
 ```

**Comment by georules** [comment]
I confirm this problem -- I'm noticing it only on the number% clicks.  Do you see it happening with the colors?

**Comment by gelicia** [comment]
clicking on the line anywhere causes the problem for me.

**Comment by enjalot** [comment]
i was also able to reproduce by just puting rgb on a single line and then trying to click anywhere on it.

**Comment by enjalot** [comment]
I found the problem! it was a missing global on the rgb regex. should work with latest push.
