### ISSUE TITLE
slider not recognizing decimal as part of the number

### ISSUE THREAD

**Issue by zanarmstrong** [enjalot/Inlet#20]
A css fill-opacity was .2, with no leading 0.  When I used a slider on it, it treated the 2 as the value rather than the .2.  In other words, it went from .2, .3, .4, .5, .6, ... , .9, .10, .11, .12

This was resolved if I switched the .2 to 0.2 and tried again.  Then it recognized that the starting value was 0.2 and not 2.

**Comment by enjalot** [comment]
thanks for pointing this out, it was a pretty easy fix :+1:
