### ISSUE TITLE
Check Boxes for "true" & "false"

### ISSUE THREAD

**Issue by curran** [enjalot/Inlet#23]
Feature request: Have a check box appear over boolean values. Numbers have sliders, colors have a color picker, booleans would be sweet to edit also.

**Comment by georules** [comment]
ask and ye shall receive!

**Comment by curran** [comment]
This is awesome! It works on my machine. Thanks for doing this work.

**Comment by georules** [comment]
Yeah it was fun :)  Doing it made me think that we might consider re-organizing the code in src/inlet.js so that adding features like this has more structure.

**Comment by mikethedj4** [comment]
This issue should be closed
