### ISSUE TITLE
Does Not Work on Touch Devices

### ISSUE THREAD

**Issue by mikethedj4** [enjalot/Inlet#29]
The color picker and numeric slider were not designed for mobile support. 

Some people may still want to use the Thistle color picker. So I forked the project using the [Color Picker JSColor](http://jscolor.com/) instead, because I needed touch support.  

You can view the fork at https://github.com/mikethedj4/Inlet if interested.

**Comment by curran** [comment]
This is awesome! Great work.

**Comment by curran** [comment]
I also prefer the JSColor UI. and on many occasions I experienced a bug in the Thistle color picker where if the lightness is 0 (black), the dot cannot be dragged out of the center. My only concern though is the [restrictive JSColor Licensing](http://jscolor.com/license/?type=dev). It looks like the author is charging $25 for a non GPL licensed version, and if you use the GPL licensed version, you may not use it in commercial code.

You may want to have a look at https://github.com/bgrins/spectrum . This is released under what looks like the MIT license, and also has mobile support.

**Comment by mikethedj4** [comment]
I dislike Spectrum. I'm working on integrating [JQuery MiniColors](http://labs.abeautifulsite.net/jquery-minicolors/index.html) into Inlet so I can use it with my app [kodeWeave](http://kodeweave.sourceforge.net/). (Haven't figured out how to get Alpha to work with Inlet yet)

**Comment by enjalot** [comment]
Thanks for working towards this! what do you mean by "pass into" in this case?
hsla should be supported via this regex https://github.com/enjalot/Inlet/blob/master/src/inlet.js#L343
but rgb needs to have it's regex improved to support rgba still.

is there a reason you closed this if you are still working on it?

**Comment by mikethedj4** [comment]
I closed because the main objective was completed (thus porting a touch friendly color picker). Getting alpha transparency to work is a separate issue.
